This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./FS_Latex.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file FS_Latex.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (22 comparisons).
Generating output file FS_Latex.acr....done (15 lines written, 0 warnings).
Output written in FS_Latex.acr.
Transcript written in FS_Latex.alg.
